# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='user_name',
        ),
    ]
