# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20160913_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='postcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
