# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160914_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='postcount',
            new_name='post_count',
        ),
    ]
