# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 16:52
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160914_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to=blog.models.get_image_path)),
                ('content_url', models.CharField(max_length=100)),
                ('blogger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.UserDetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
