# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 19:28
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(upload_to=blog.models.get_image_path),
        ),
    ]
