# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 21:25
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160924_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=blog.models.get_image_path),
        ),
    ]
