# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160924_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
