# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogdata_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogdata',
            name='image',
        ),
    ]
