# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_blogdata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
