# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160925_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='post_number',
            field=models.IntegerField(default=0),
        ),
    ]
