# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blogdata_post_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='active',
            field=models.BooleanField(default=1),
        ),
    ]
